#!/bin/sh

if test $# -ne 3 -a $# -ne 4; then
    echo "Usage: $0 <cluster_name> <namespace> <dir> [alternate_kube_context]"
    exit 1
fi

WORK_DIR=/tmp/naiscaper
CLUSTER=$1
NAMESPACE=$2
NAISCAPER_DIR=$3
KUBE_CONTEXT=${4:-${1}}

mkdir -p $WORK_DIR
rm -f $WORK_DIR/*
files=`ls $NAISCAPER_DIR/base/*.yaml $NAISCAPER_DIR/clusters/$CLUSTER/*.yaml | awk -F/ '{print $NF}' | sort | uniq`
for file in $files; do
    if test ! -f $NAISCAPER_DIR/clusters/$CLUSTER/`basename $file .yaml`.ignore; then
        if test -s $NAISCAPER_DIR/base/$file -a -s $NAISCAPER_DIR/clusters/$CLUSTER/$file; then
            echo $file: merging files
            yq merge $NAISCAPER_DIR/clusters/$CLUSTER/$file $NAISCAPER_DIR/base/$file > $WORK_DIR/$file
        elif test -s $NAISCAPER_DIR/base/$file; then
            echo $file: using base file
            cp $NAISCAPER_DIR/base/$file $WORK_DIR/
        elif test -s $NAISCAPER_DIR/clusters/$CLUSTER/$file; then
            echo $file: using cluster file
            cp $NAISCAPER_DIR/clusters/$CLUSTER/$file $WORK_DIR/
        fi
    fi
done

landscaper -v --env $CLUSTER --context $KUBE_CONTEXT --namespace $NAMESPACE apply $WORK_DIR/*.yaml
