#!/usr/bin/env bash
if test $# -ne 3; then
  echo "Usage: $0 <base_dir> <override_dir> <output_dir>"
  exit 1
fi

yq=$(command -v yq)
base_dir=$1
override_dir=$2
output_dir=$3

mkdir -p "$output_dir"
rm -f "$output_dir/*"
files=$(find "${base_dir}" "${override_dir}" -iname "*.yaml" -exec basename {} \; | sort | uniq)

for file in $files; do
  if test ! -f "$override_dir/$(basename "$file" .yaml).ignore"; then
    if test -s "$base_dir/$file" -a -s "$override_dir/$file"; then
      echo "$file": merging files
      $yq merge "$override_dir/$file" "$base_dir/$file" > "$output_dir/$file"
    elif test -s "$base_dir/$file"; then
      echo "$file": using base file
      cp "$base_dir/$file" "$output_dir/"
    elif test -s "$override_dir/$file"; then
      echo "$file": using cluster file
      cp "$override_dir/$file" "$output_dir/"
    fi
  fi
done
